### ISSUE TITLE
spyk broken for class hierarchies

### ISSUE THREAD

**Issue by dan-van** [oleksiyp/mockk#5]
Thanks, mockk is looking really promising!
Howver, it seems like there are a few issues with spy when the object inherits from a base class.
Some examples:

the 'logger' fields can be anything, but it is a pretty common pattern, and one where you may have private final fields with the same name in a class and its superclass.
```
        open class BaseTest(val someReference:String) {
            private var logger: org.slf4j.Logger = LoggerFactory.getLogger(BaseTest::class.java)
            open fun doLog() {
                logger.info("Base $someReference")
            }
        }

        class SpyTest() : BaseTest("A spy"){
            private var logger: org.slf4j.Logger = LoggerFactory.getLogger(SpyTest::class.java)
            override fun doLog() {
                logger.info("spyTest")
            }
        }

        val spyObj = spyk<BaseTest>(SpyTest()) // this breaks.
//        val spyObj = spyk<SpyTest>(SpyTest()) // uncomment this as a semi-workaround
        every {
            spyObj.doLog()
        } just Runs.apply{println("Intercepted")}
        // but superclass fields are not set correctly, so this fails too:
        assert(spyObj.someReference != null)
        spyObj.doLog()
```

**Comment by oleksiyp** [comment]
Thanks for reporting. Let me check this example.

**Comment by oleksiyp** [comment]
Okay, so this to be fixed in 1.5.2 soon.

There is few points mixed here:

1. Correct way to create spy is just  spyk(SpyTest()) to copy everything from object or spyk<SpyTest>() to call default constructor (specifying different than object type type parameter looks like error prone. will check how to make it better)
2. `just Runs.apply{println("Intercepted")}` just does not work. It's pretty synthetic construct which actually do nothing on response. println is executed but at declaration time, not at interception time.
3. There is a bug in spy initialization code that doesn't take into account base classes (fixed, thanks for pointing out)

**Comment by oleksiyp** [comment]
@dan-van can you check 1.5.2 version?

Something alike this should work:

```kotlin
        open class BaseTest(val someReference:String) {
            private var logger: org.slf4j.Logger = LoggerFactory.getLogger(BaseTest::class.java)
            open fun doLog() {
                logger.info("Base $someReference")
            }
        }

        class SpyTest() : BaseTest("A spy"){
            private var logger: org.slf4j.Logger = LoggerFactory.getLogger(SpyTest::class.java)
            override fun doLog() {
                logger.info("spyTest")
            }
        }

        val spyObj = spyk(SpyTest())
        every {
            spyObj.doLog()
        } answers {
            println("Intercepted");
            callOriginal();
        }

        assert(spyObj.someReference != null)
        spyObj.doLog()
```

**Comment by oleksiyp** [comment]
Looks like issue is resolved. @dan-van Thanks for reporting again
